Replacing TABs with spaces.

diff --git a/ping-xray b/ping-xray
--- a/ping-xray
+++ b/ping-xray
@@ -59,6 +59,9 @@
 # For example if you run:
 #    ./ping-xray-simple 192.168.3.1 24.212.218.1 8.8.8.8 google.com gw1.ibllc.com gw2.ibllc.com
 #
+# or with optional labels (Optional label stars with "_", no spaces allowed)
+#    ./ping-xray-simple 192.168.3.1_local_router 24.212.218.1_ISP-gateway 8.8.8.8_NS-server google.com_google gw1.ibllc.com gw2.ibllc.com
+#
 # Pinger creates 'ping-xray-output/' folder and writes logs: one log file per target plus one
 # CSV file with Round-trip delay time (milliseconds) for all targets (one line = one second).
 # Here's an example output of ping-xray-simple, which shows you last few lines of monitored.
@@ -150,7 +153,7 @@ SLEEP_BEFORE_NEXT_PING_MS=1000
 #
 REFRESH_SCREEN_EACH_N_SECONDS=2
 
-# cd to script folder and get it's full absolute path (instead of relative path)
+# Change directory into the script folder and get it's full absolute path (instead of relative path)
 BASE_DIR=$(dirname $0)
 cd ${BASE_DIR}
 BASE_DIR=`pwd`
@@ -159,13 +162,13 @@ BASE_DIR=`pwd`
 # If you prefer other location, specify it here:
 LOG_DIR="${HOME}/.ping-xray"
 
-# script will need to know it's name, since child processes (each target pinged in separate
+# Script will need to know it's name, since child processes (each target pinged in separate
 # background process) will need to check if parent process is still alive (otherwise child
 # terminates itself). On linux the parend process would have same name as this script name,
 # but on OS-X the parent process name is "/bin/bash".
 SCRIPT_NAME=`basename "$0"`
 
-# ps command truncates the script name down to 15 characters. There are forms of ps command
+# The 'ps' command truncates the script name down to 15 characters. There are forms of ps command
 # which would allow to have process name not truncates, but we need one that reliably works
 # on both Linux and OS-X, so it might be easier to allow "ps" command to shorten the script
 # name and we'll do the same for proper regexp match (from child process when it checks if
@@ -173,42 +176,42 @@ SCRIPT_NAME=`basename "$0"`
 #
 SCRIPT_NAME_TRUNC15="${SCRIPT_NAME:0:15}"
 
-# Check dependency: Is fping installed?
+# Check dependency: is 'fping' installed? Error out if not.
 which fping > /dev/null
 if [ $? -ne 0 ]; then
     echo "error: dependency 'fping' is not installed. Please install 'fping' and try again." >&2
     exit 1
 fi
 
-# make sure $LOG_DIR exists
-if [ ! -d ${LOG_DIR} ]; then
-    echo "creating log folder: ${LOG_DIR}"
-    mkdir -p ${LOG_DIR}
-    RES=$?
-    if [ ${RES} -ne 0 ]; then
-	echo "error: failed to create folder ${LOG_DIR}" >&2
-	exit 1
-    fi
-fi
-
-# if no arguments specified report an error and exit
+# If no arguments specified report an error and exit.
 if [ "${1}" == "" ]; then
-    echo "error: please specify at least one target to ping" >&2
+    echo "Error: please specify at least one target to ping" >&2
     exit 1
 fi
 
-# construct array of targets
+# Make sure ${LOG_DIR} exists, create if missing.
+if [ ! -d ${LOG_DIR} ]; then
+    echo "Note: creating log folder: ${LOG_DIR}"
+    mkdir -p ${LOG_DIR}
+    RES=$?
+    if [ ${RES} -ne 0 ]; then
+        echo "Error: failed to create folder ${LOG_DIR}" >&2
+        exit 1
+    fi
+fi
+
+# Construct array of targets.
 TARGETS=( "$@" )
 TARGETS_LENGTH=${#TARGETS[@]}
 TARGETS_LAST_INDEX=$(( TARGETS_LENGTH - 1 ))
-echo "array length: ${TARGETS_LENGTH}"
-echo "TARGETS_LAST_INDEX: ${TARGETS_LAST_INDEX}"
+# echo "debug: TARGETS array length: ${TARGETS_LENGTH}"
+# echo "debug: TARGETS_LAST_INDEX: ${TARGETS_LAST_INDEX}"
 
-# declare an array of target's labels. Those are optional and can be given by user
-# in the following form: "1.2.3.4_Wi-fi_Router"
+# Declare an array of target's labels. Those are optional and can be given by user
+# in the following form: "1.2.3.4_Wi-fi_Router" (Optional label stars with "_", no spaces allowed)
 declare -a TARGETS_LABELS
 
-# let's review targets and separate/isolate optional labels (stars with "_")
+# Let's review targets and separate/isolate optional labels (Optional label stars with "_", no spaces allowed)
 shopt -s extglob  # https://stackoverflow.com/a/41422027/7022062 - we'll replace all "_" with " " inside the labels
 for idx in "${!TARGETS[@]}"; do
     if [[ ${TARGETS[$idx]} =~ ([^_]+)_(.*) ]]; then
@@ -481,14 +484,14 @@ function check_if_parent_is_alive_or_exit() {
     fi
 }
 
-# some defaults (not need to change, so kinda hidden deep down here:)
+# Some defaults (not need to change, so kinda hidden deep down here:)
 NUMBER_OF_PINGS=1
 PING_TIMEOUT_S=1
 
-# try to get OS name (works on OS-X and Linux)
+# Try to get OS name (works on OS-X and Linux)
 OS_NAME=`uname -s`
 
-# sanity check - we have expected version name
+# Sanity check - we have expected version name
 # "if" statement left in a "long form" here just as a template (to be reused later on for some suddle differences between OSes)
 if [ "${OS_NAME}" == "Linux" ]; then
     : # we're running on linux
@@ -499,7 +502,7 @@ else
     exit 1
 fi
 
-# note: we're adding 'localhost' as a target, so we have reliable response each second from at least 1
+# Note: we're adding 'localhost' as a target, so we have reliable response each second from at least 1
 # target (so we can jump to firm assumption that other's failed if not deliveren during N-th iteration) (c) dimon.ca (patent pending;)
 #
 # note: "-i 10" added instead of "-i 1" so non-priveleted (non-root) users can use the tool just as well, otherwise following errors:
@@ -511,7 +514,7 @@ fi
 
 
 
-# get currrent date/time (works on Linux & OS-X)
+# Get currrent date/time (works on Linux & OS-X)
 date=$(date +'%Y-%m-%d %H:%M:%S')
 read Y M D h m s <<< ${date//[-: ]/ }
 
@@ -539,7 +542,7 @@ for idx in "${!TARGETS[@]}"; do
     fi
 done
 
-# write comma-separated headers to CSV file
+# Write comma-separated headers to CSV file
 join_by , "${TARGETS[@]}"
 echo "epoch_s,${join_by_result}" > ${LOG_FILE_CSV}
 
@@ -560,10 +563,10 @@ fi
 # http://stackoverflow.com/questions/4165135/how-to-use-while-read-bash-to-read-the-last-line-in-a-file-if-theres-no-new
 #
 function main_pinger_loop() {
-declare -a OUTPUT_PER_TARGET_SYM
-declare -a OUTPUT_PER_TARGET_RTT
+declare -a OUTPUT_PER_TARGET_SYM  # Array of symbols to draw for each ping probe
+declare -a OUTPUT_PER_TARGET_RTT  # Array of corresponding RTT (millisecond) values we got from each ping probe
 
-epoch_s=`date +%s`
+epoch_s=$( date +%s )
 last_minute_start_epoch_s=$(( epoch_s / 60 * 60 ))
 
 previous_iteration_count=0  # "previous_iteration_count" comes from fping output (see int value in square brackets in example output below)
@@ -649,21 +652,21 @@ while IFS='' read -r line || [[ -n "${line}" ]]; do
 	    # we wrote all csv values, add EOL to CSV file
 	    echo >> ${LOG_FILE_CSV}
 
-	    #    3) reset "per-target" buckets before we start recording new bunch (new 1sec bucket with new incremented $iteration_count)
+	    #    3) reset "per-target" buckets before we start recording new bunch (new 1sec bucket with new incremented ${iteration_count} )
 	    unset OUTPUT_PER_TARGET_SYM
 	    previous_iteration_count="${iteration_count}"
 	fi
 
-	# identify current line target's index 
+	# Identify current line target's index 
 	# (we get intermixed results from fping, sometimes some targets can be missing if ping make it in 1s)
 	get_target_index "${target}"
 	target_idx=$?
 	
-	# get symbol, which will characterize the ping timing (according to get_sym_for_rtt_ms_rounded() "table")
+	# Get symbol, which will characterize the ping timing (according to get_sym_for_rtt_ms_rounded() "table")
 	# function sets $sym_for_rtt_ms_rounded
 	get_sym_for_rtt_ms_rounded
 	
-	# store result
+	# Store result: symbol and RTT (in milliseconds)
 	OUTPUT_PER_TARGET_SYM[$target_idx]=$sym_for_rtt_ms_rounded
 	OUTPUT_PER_TARGET_RTT[$target_idx]=$rtt_ms
 
diff --git a/ping-xray-simple b/ping-xray-simple
--- a/ping-xray-simple
+++ b/ping-xray-simple
@@ -40,17 +40,17 @@
 # or some other "mysterious" BS.
 #
 # And here comes the ping-xray, which allows you to:
-#	- ping multiple targets simultaneously
-#	- visually see the output with 1 second resolution
-#	  (one terminlal can show 2-3 hours history for lots of target hosts)!
-#	- create log files with unique filename, so you have it for the record.
-#	  (log file would have timestamp in it's name, so it is safe to restart the tool
-#	   without loosing any of the previus data)
-#	- create one CSV file with all targets exact round-trip delay time (exact milliseconds)
+#        - ping multiple targets simultaneously
+#        - visually see the output with 1 second resolution
+#          (one terminlal can show 2-3 hours history for lots of target hosts)!
+#        - create log files with unique filename, so you have it for the record.
+#          (log file would have timestamp in it's name, so it is safe to restart the tool
+#           without loosing any of the previus data)
+#        - create one CSV file with all targets exact round-trip delay time (exact milliseconds)
 #
 # ping-xray comes in two flaivors:
-#	- ping-xray-simple
-#	- ping-xray (fancy ascii "gui")
+#        - ping-xray-simple
+#        - ping-xray (fancy ascii "gui")
 #
 # First tool "ping-xray-simple" is just couple hundred lines of code script, which takes
 # arbitrary number of targets to poing (IP or hostnames with optional description, see example below),
@@ -127,9 +127,9 @@
 # what causing those problems on your end. ;)
 #
 # Usually I'd recommend to run the pinger for the whole trading day and ping at least 3 targets:
-#	1) your router (on your LAN)
-#	2) your ISP gateway (1st IP outside your lan on the ISP end)
-#	3) some more distant public targets, like google.com and your broker's server.
+#        1) your router (on your LAN)
+#        2) your ISP gateway (1st IP outside your lan on the ISP end)
+#        3) some more distant public targets, like google.com and your broker's server.
 #
 # If your broker (or other target server) does not allow ICMP, then you can use "TCP SYN Ping"
 # with much less aggressive rate of you ping requests (ping-xray not yet supports TCP SYN Ping).
@@ -195,8 +195,8 @@ if [ ! -d ${LOG_DIR} ]; then
     mkdir -p ${LOG_DIR}
     RES=$?
     if [ ${RES} -ne 0 ]; then
-	echo "error: failed to create folder ${LOG_DIR}" >&2
-	exit 1
+        echo "error: failed to create folder ${LOG_DIR}" >&2
+        exit 1
     fi
 fi
 
@@ -221,9 +221,9 @@ declare -a TARGETS_LABELS
 shopt -s extglob  # https://stackoverflow.com/a/41422027/7022062 - we'll replace all "_" with " " inside the labels
 for idx in "${!TARGETS[@]}"; do
     if [[ ${TARGETS[$idx]} =~ ([^_]+)_(.*) ]]; then
-	TARGETS[$idx]="${BASH_REMATCH[1]}"		# rewrite i-th target w/o label
-	iLABEL="${BASH_REMATCH[2]}"
-	TARGETS_LABELS[$idx]="${iLABEL//+([_])/ }"	# store label
+        TARGETS[$idx]="${BASH_REMATCH[1]}"                # rewrite i-th target w/o label
+        iLABEL="${BASH_REMATCH[2]}"
+        TARGETS_LABELS[$idx]="${iLABEL//+([_])/ }"        # store label
     fi
 done
 
@@ -244,9 +244,9 @@ function get_target_index() {
     TARGET=$1
     #for (( i=0; i<${TARGETS_LENGTH}; i++ )); do
     for i in "${!TARGETS[@]}"; do
-	if [ "${TARGET}" == "${TARGETS[$i]}" ]; then
-	    return $i
-	fi
+        if [ "${TARGET}" == "${TARGETS[$i]}" ]; then
+            return $i
+        fi
     done
     return 255
 }
@@ -368,63 +368,63 @@ COLORMAP[${#COLORMAP[*]}]="\033[38;2;251;29;0;m"
 COLORMAP[${#COLORMAP[*]}]="\033[38;2;250;25;0;m"
 
 function get_sym_for_rtt_ms_rounded() {
-	if (( $rtt_ms_rounded < 100 )); then
-	    sym_for_rtt_ms_rounded="${COLORMAP[${rtt_ms_rounded%?}]}."  # '%?' is here to drop last digit, so instead of 0..999 we have 0..99
-	    return
-	elif (( $rtt_ms_rounded < 200 )); then
-	    sym_for_rtt_ms_rounded="${COLORMAP[${rtt_ms_rounded%?}]}1"
-	    return
-	elif (( $rtt_ms_rounded < 300 )); then
-	    sym_for_rtt_ms_rounded="${COLORMAP[${rtt_ms_rounded%?}]}2"
-	    return
-	elif (( $rtt_ms_rounded < 400 )); then
-	    sym_for_rtt_ms_rounded="${COLORMAP[${rtt_ms_rounded%?}]}3"
-	    return
-	elif (( $rtt_ms_rounded < 500 )); then
-	    sym_for_rtt_ms_rounded="${COLORMAP[${rtt_ms_rounded%?}]}4"
-	    return
-	elif (( $rtt_ms_rounded < 600 )); then
-	    sym_for_rtt_ms_rounded="${COLORMAP[${rtt_ms_rounded%?}]}5"
-	    return
-	elif (( $rtt_ms_rounded < 700 )); then
-	    sym_for_rtt_ms_rounded="${COLORMAP[${rtt_ms_rounded%?}]}6"
-	    return
-	elif (( $rtt_ms_rounded < 800 )); then
-	    sym_for_rtt_ms_rounded="${COLORMAP[${rtt_ms_rounded%?}]}7"
-	    return
-	elif (( $rtt_ms_rounded < 900 )); then
-	    sym_for_rtt_ms_rounded="${COLORMAP[${rtt_ms_rounded%?}]}8"
-	    return
-	elif (( $rtt_ms_rounded < 1000 )); then
-	    sym_for_rtt_ms_rounded="${COLORMAP[${rtt_ms_rounded%?}]}9"
-	    return
-	else
-	    sym_for_rtt_ms_rounded='SHOULDNEVERHAPPEN_PLEASE_FIX'  # the max expected value of RTT is 999, so this should never happen
-	fi
+        if (( $rtt_ms_rounded < 100 )); then
+            sym_for_rtt_ms_rounded="${COLORMAP[${rtt_ms_rounded%?}]}."  # '%?' is here to drop last digit, so instead of 0..999 we have 0..99
+            return
+        elif (( $rtt_ms_rounded < 200 )); then
+            sym_for_rtt_ms_rounded="${COLORMAP[${rtt_ms_rounded%?}]}1"
+            return
+        elif (( $rtt_ms_rounded < 300 )); then
+            sym_for_rtt_ms_rounded="${COLORMAP[${rtt_ms_rounded%?}]}2"
+            return
+        elif (( $rtt_ms_rounded < 400 )); then
+            sym_for_rtt_ms_rounded="${COLORMAP[${rtt_ms_rounded%?}]}3"
+            return
+        elif (( $rtt_ms_rounded < 500 )); then
+            sym_for_rtt_ms_rounded="${COLORMAP[${rtt_ms_rounded%?}]}4"
+            return
+        elif (( $rtt_ms_rounded < 600 )); then
+            sym_for_rtt_ms_rounded="${COLORMAP[${rtt_ms_rounded%?}]}5"
+            return
+        elif (( $rtt_ms_rounded < 700 )); then
+            sym_for_rtt_ms_rounded="${COLORMAP[${rtt_ms_rounded%?}]}6"
+            return
+        elif (( $rtt_ms_rounded < 800 )); then
+            sym_for_rtt_ms_rounded="${COLORMAP[${rtt_ms_rounded%?}]}7"
+            return
+        elif (( $rtt_ms_rounded < 900 )); then
+            sym_for_rtt_ms_rounded="${COLORMAP[${rtt_ms_rounded%?}]}8"
+            return
+        elif (( $rtt_ms_rounded < 1000 )); then
+            sym_for_rtt_ms_rounded="${COLORMAP[${rtt_ms_rounded%?}]}9"
+            return
+        else
+            sym_for_rtt_ms_rounded='SHOULDNEVERHAPPEN_PLEASE_FIX'  # the max expected value of RTT is 999, so this should never happen
+        fi
 }
 
 # Tried some alternatives.. may be some "ascii heat map" can be used here
 # to make output more human-readable. Colours would be a good idea, but not for v.0.0.1 ;)
 #
 #function get_sym_for_rtt_ms_rounded_ALTERNATIVE3() {
-#	if (( $rtt_ms_rounded < 200 )); then
-#	    sym_for_rtt_ms_rounded=' '
-#	    return
-#	elif (( $rtt_ms_rounded >= 200 )) && (( $rtt_ms_rounded < 400 )); then
-#	    sym_for_rtt_ms_rounded='.'
-#	    return
-#	elif (( $rtt_ms_rounded >= 400 )) && (( $rtt_ms_rounded < 600 )); then
-#	    sym_for_rtt_ms_rounded='_'
-#	    return
-#	elif (( $rtt_ms_rounded >= 600 )) && (( $rtt_ms_rounded < 800 )); then
-#	    sym_for_rtt_ms_rounded='='
-#	    return
-#	elif (( $rtt_ms_rounded >= 800 )); then
-#	    sym_for_rtt_ms_rounded='z'
-#	    return
-#	else
-#	    sym_for_rtt_ms_rounded='SHOULDNEVERHAPPEN'
-#	fi
+#        if (( $rtt_ms_rounded < 200 )); then
+#            sym_for_rtt_ms_rounded=' '
+#            return
+#        elif (( $rtt_ms_rounded >= 200 )) && (( $rtt_ms_rounded < 400 )); then
+#            sym_for_rtt_ms_rounded='.'
+#            return
+#        elif (( $rtt_ms_rounded >= 400 )) && (( $rtt_ms_rounded < 600 )); then
+#            sym_for_rtt_ms_rounded='_'
+#            return
+#        elif (( $rtt_ms_rounded >= 600 )) && (( $rtt_ms_rounded < 800 )); then
+#            sym_for_rtt_ms_rounded='='
+#            return
+#        elif (( $rtt_ms_rounded >= 800 )); then
+#            sym_for_rtt_ms_rounded='z'
+#            return
+#        else
+#            sym_for_rtt_ms_rounded='SHOULDNEVERHAPPEN'
+#        fi
 #}
 
 ################################################################################
@@ -482,10 +482,10 @@ function check_if_parent_is_alive_or_exit() {
     # check if parent process is still running (otherwise kill oneself)
     SNIFFING_PARENT_NAME="`ps -p $$ -o comm=`"
     if [[ "${SNIFFING_PARENT_NAME}" =~ "bash" ]] || [[ "${SNIFFING_PARENT_NAME}" =~ "${SCRIPT_NAME_TRUNC15}" ]]; then
-	: # echo "parent is alive"
+        : # echo "parent is alive"
     else
-	#echo "parent is dead"
-	exit 0
+        #echo "parent is dead"
+        exit 0
     fi
 }
 
@@ -528,7 +528,7 @@ read Y M D h m s <<< ${date//[-: ]/ }
 # Note: "per target" is formed by concatination of "basename" with particular target: ${LOG_FILE_BASENAME}_${TARGETS[i]}
 #
 LOG_FILES_BASENAME="${LOG_DIR}/${Y}${M}${D}_${h}_${m}_${s}"
-LOG_FILE_CSV="${LOG_FILES_BASENAME}.csv"				# this file is simple CSV with "epoch_s", "rtt_ms_target-1", "rtt_ms_target-2", etc.
+LOG_FILE_CSV="${LOG_FILES_BASENAME}.csv"                                # this file is simple CSV with "epoch_s", "rtt_ms_target-1", "rtt_ms_target-2", etc.
 
 echo "csv log file: ${LOG_FILE_CSV}"
 
@@ -540,8 +540,8 @@ for idx in "${!TARGETS[@]}"; do
     # and then as other user with less priveleges, so let's check:
     RES=$?
     if [ $RES -ne 0 ]; then
-	echo "Error: failed write to file '${LOG_FILES_BASENAME}_${iTARGET}', check permissions. Will exit now..." >&2
-	exit 1
+        echo "Error: failed write to file '${LOG_FILES_BASENAME}_${iTARGET}', check permissions. Will exit now..." >&2
+        exit 1
     fi
 done
 
@@ -584,92 +584,92 @@ while IFS='' read -r line || [[ -n "${line}" ]]; do
     # bash does support regexp: https://stackoverflow.com/a/44490624/7022062
     # parse line and extract values
     if [[ $line =~ \[([0-9]+)(\.[0-9]+\] +)([^ ]+)\ +:\ \[([0-9]+)\].*bytes,\ ([^ ]+)\ ms\ \(([^ ]+)\ avg ]]; then
-	epoch_s="${BASH_REMATCH[1]}"
-	target="${BASH_REMATCH[3]}"
-	per_target_log="${LOG_FILES_BASENAME}_${TARGETS[i]}"
-	iteration_count="${BASH_REMATCH[4]}"
-	rtt_ms="${BASH_REMATCH[5]}"
-	rtt_ms_rounded="`printf %.0f $rtt_ms`"
-	avg_ms="${BASH_REMATCH[6]}"
-	this_minute_start_epoch_s=$(( epoch_s / 60 * 60 ))
+        epoch_s="${BASH_REMATCH[1]}"
+        target="${BASH_REMATCH[3]}"
+        per_target_log="${LOG_FILES_BASENAME}_${TARGETS[i]}"
+        iteration_count="${BASH_REMATCH[4]}"
+        rtt_ms="${BASH_REMATCH[5]}"
+        rtt_ms_rounded="`printf %.0f $rtt_ms`"
+        avg_ms="${BASH_REMATCH[6]}"
+        this_minute_start_epoch_s=$(( epoch_s / 60 * 60 ))
         if (( $previous_iteration_count != $iteration_count )); then
-	    # New 1sec bunch of pings coming. They come every 1sec and have same $iteration_count value.
-	    # We might miss some replies from slow targets (which took >1sec to reply)). Next steps are:
-	    #    1) check if current minute is over
-	    #       then print new line beginning for GUI (only for human-readable aspect, not for csv logging. csv is simply "flat")
-	    #    2) report collected rtt_ms or 'F' for missing ones (for which we failed to get replies withing previous 1sec bucket)
-	    #       on both "GUI" and csv files
-	    #    3) reset "per-target" buckets before we start recording new bunch (new 1sec bucket with new incremented $iteration_count)
-	    #    4) store new (1st) value for the next bucket
+            # New 1sec bunch of pings coming. They come every 1sec and have same $iteration_count value.
+            # We might miss some replies from slow targets (which took >1sec to reply)). Next steps are:
+            #    1) check if current minute is over
+            #       then print new line beginning for GUI (only for human-readable aspect, not for csv logging. csv is simply "flat")
+            #    2) report collected rtt_ms or 'F' for missing ones (for which we failed to get replies withing previous 1sec bucket)
+            #       on both "GUI" and csv files
+            #    3) reset "per-target" buckets before we start recording new bunch (new 1sec bucket with new incremented $iteration_count)
+            #    4) store new (1st) value for the next bucket
 
-	    # 1) checking if current minute is over
-	    #     method-1: [by mod  $(( 1497370200 % 60 )) == 0 ] <-- this method is no good.. if we skipped this exact sec, we're screwed and will have to wait/hope till the next minute start
-	    #     method-2: compare "this minute start epoch sec" to the previously reported: this_minute_start_epoch_s=$(( epoch_s / 60 * 60 ))    <-- METHOD WORKS SO MUCH BETTER!!
-	    if (( $last_minute_start_epoch_s != $this_minute_start_epoch_s )); then
-		# yes, a new minute started!
-		last_minute_start_epoch_s=$this_minute_start_epoch_s
-		
-		# Function get_YYYYMMDDHHMM_by_epoch_s() sets result to: YYYYMMDDHHMM_by_epoch_s
-		get_YYYYMMDDHHMM_by_epoch_s $epoch_s
-		
-		# Print end of line and new prefix (date/time) to all target files
-		for idx in "${!TARGETS[@]}"; do
-		    iTARGET="${TARGETS[$idx]}"
-		    echo >> "${LOG_FILES_BASENAME}_${iTARGET}"
-		    echo -n "${YYYYMMDDHHMM_by_epoch_s} " >> "${LOG_FILES_BASENAME}_${iTARGET}"
-		done
-	    fi
+            # 1) checking if current minute is over
+            #     method-1: [by mod  $(( 1497370200 % 60 )) == 0 ] <-- this method is no good.. if we skipped this exact sec, we're screwed and will have to wait/hope till the next minute start
+            #     method-2: compare "this minute start epoch sec" to the previously reported: this_minute_start_epoch_s=$(( epoch_s / 60 * 60 ))    <-- METHOD WORKS SO MUCH BETTER!!
+            if (( $last_minute_start_epoch_s != $this_minute_start_epoch_s )); then
+                # yes, a new minute started!
+                last_minute_start_epoch_s=$this_minute_start_epoch_s
+                
+                # Function get_YYYYMMDDHHMM_by_epoch_s() sets result to: YYYYMMDDHHMM_by_epoch_s
+                get_YYYYMMDDHHMM_by_epoch_s $epoch_s
+                
+                # Print end of line and new prefix (date/time) to all target files
+                for idx in "${!TARGETS[@]}"; do
+                    iTARGET="${TARGETS[$idx]}"
+                    echo >> "${LOG_FILES_BASENAME}_${iTARGET}"
+                    echo -n "${YYYYMMDDHHMM_by_epoch_s} " >> "${LOG_FILES_BASENAME}_${iTARGET}"
+                done
+            fi
 
-	    #    2) report collected rtt_ms or 'X' for missing ones (for which we failed to get replies withing previous 1sec bucket)
-	    #       on both "GUI" and csv files
-	    echo -n "${epoch_s}," >> ${LOG_FILE_CSV}
-	    for idx in "${!TARGETS[@]}"; do
-		iTARGET="${TARGETS[$idx]}"
-		iSYM="${OUTPUT_PER_TARGET_SYM[$idx]}"
-		iRTT_MS="${OUTPUT_PER_TARGET_RTT[$idx]}"
-		if [ "${iSYM}" == "" ]; then
-		    # blank value, means this target (F)ailed to reply within 1sec
-		    #
-		    # Terminal escape colours explained: https://askubuntu.com/questions/558280/changing-colour-of-text-and-background-of-terminal
-		    #     printf '\e[38;5;196m Foreground color: red\n'
-		    #     printf '\e[48;5;0m Background color: black\n'
-		    #
-		    # Or by RGB components:
-		    #     printf '\e[38;2;255;0;0m Foreground color: red\n'
-		    #     printf '\e[48;2;0;0;0m Background color: black\n'
-		
-		    #iSYM="\e[38;5;226m\e[48;5;196mG\e[0m"	# why this doesn't work?
-		    # iSYM="\033(0x\033(B" 			# while this one works fine.
-		
-		    iSYM="\033[38;5;226m\033[48;5;196mX\033[0m"  # "X" looks better for X-Ray tool ;)
-		    #iSYM="\033[38;5;226m\033[48;5;196mF\033[0m"  # "F"
-		fi
-		echo -n "${iSYM}" >> "${LOG_FILES_BASENAME}_${iTARGET}"
-		echo -n "${iRTT_MS}" >> ${LOG_FILE_CSV}
-		if [[ $idx != $TARGETS_LAST_INDEX ]]; then
-		    echo -n ',' >> ${LOG_FILE_CSV}
-		fi
-	    done
-	    # we wrote all csv values, add EOL to CSV file
-	    echo >> ${LOG_FILE_CSV}
+            #    2) report collected rtt_ms or 'X' for missing ones (for which we failed to get replies withing previous 1sec bucket)
+            #       on both "GUI" and csv files
+            echo -n "${epoch_s}," >> ${LOG_FILE_CSV}
+            for idx in "${!TARGETS[@]}"; do
+                iTARGET="${TARGETS[$idx]}"
+                iSYM="${OUTPUT_PER_TARGET_SYM[$idx]}"
+                iRTT_MS="${OUTPUT_PER_TARGET_RTT[$idx]}"
+                if [ "${iSYM}" == "" ]; then
+                    # blank value, means this target (F)ailed to reply within 1sec
+                    #
+                    # Terminal escape colours explained: https://askubuntu.com/questions/558280/changing-colour-of-text-and-background-of-terminal
+                    #     printf '\e[38;5;196m Foreground color: red\n'
+                    #     printf '\e[48;5;0m Background color: black\n'
+                    #
+                    # Or by RGB components:
+                    #     printf '\e[38;2;255;0;0m Foreground color: red\n'
+                    #     printf '\e[48;2;0;0;0m Background color: black\n'
+                
+                    #iSYM="\e[38;5;226m\e[48;5;196mG\e[0m"        # why this doesn't work?
+                    # iSYM="\033(0x\033(B"                         # while this one works fine.
+                
+                    iSYM="\033[38;5;226m\033[48;5;196mX\033[0m"  # "X" looks better for X-Ray tool ;)
+                    #iSYM="\033[38;5;226m\033[48;5;196mF\033[0m"  # "F"
+                fi
+                echo -n "${iSYM}" >> "${LOG_FILES_BASENAME}_${iTARGET}"
+                echo -n "${iRTT_MS}" >> ${LOG_FILE_CSV}
+                if [[ $idx != $TARGETS_LAST_INDEX ]]; then
+                    echo -n ',' >> ${LOG_FILE_CSV}
+                fi
+            done
+            # we wrote all csv values, add EOL to CSV file
+            echo >> ${LOG_FILE_CSV}
 
-	    #    3) reset "per-target" buckets before we start recording new bunch (new 1sec bucket with new incremented $iteration_count)
-	    unset OUTPUT_PER_TARGET_SYM
-	    previous_iteration_count="${iteration_count}"
-	fi
+            #    3) reset "per-target" buckets before we start recording new bunch (new 1sec bucket with new incremented $iteration_count)
+            unset OUTPUT_PER_TARGET_SYM
+            previous_iteration_count="${iteration_count}"
+        fi
 
-	# identify current line target's index 
-	# (we get intermixed results from fping, sometimes some targets can be missing if ping make it in 1s)
-	get_target_index "${target}"
-	target_idx=$?
-	
-	# get symbol, which will characterize the ping timing (according to get_sym_for_rtt_ms_rounded() "table")
-	# function sets $sym_for_rtt_ms_rounded
-	get_sym_for_rtt_ms_rounded
-	
-	# store result
-	OUTPUT_PER_TARGET_SYM[$target_idx]=$sym_for_rtt_ms_rounded
-	OUTPUT_PER_TARGET_RTT[$target_idx]=$rtt_ms
+        # identify current line target's index 
+        # (we get intermixed results from fping, sometimes some targets can be missing if ping make it in 1s)
+        get_target_index "${target}"
+        target_idx=$?
+        
+        # get symbol, which will characterize the ping timing (according to get_sym_for_rtt_ms_rounded() "table")
+        # function sets $sym_for_rtt_ms_rounded
+        get_sym_for_rtt_ms_rounded
+        
+        # store result
+        OUTPUT_PER_TARGET_SYM[$target_idx]=$sym_for_rtt_ms_rounded
+        OUTPUT_PER_TARGET_RTT[$target_idx]=$rtt_ms
 
     fi
 
